Pitch message onboarding
shapeitapp/shapeit-github-app pull request #2
Opened 2023-11-03 18:20 UTC by Amzani

Demo

1. Go to https://github.com/samz-test/shapeitapp-actions-tests/issues/new
2. Create an issue with `pitch label`
3. A comment should appear

Example https://github.com/samz-test/shapeitapp-actions-tests/issues/11

2023-11-06 09:56 UTC, fmvilas requested changes
Super pumped this is coming! 🙌 

Left some comments but it's mostly about cleaning console.logs 😄

2023-11-06 09:56 UTC, fmvilas commented on index.js
> +    console.log(`projects_v2_item.edited triggered`)
```suggestion
```

2023-11-06 09:56 UTC, fmvilas commented on index.js
> +        console.log("That's a pitch or a Bet")
```suggestion
```

2023-11-06 09:56 UTC, fmvilas commented on index.js
> +    }
```suggestion
    }
```

2023-11-06 09:56 UTC, fmvilas commented on index.js
> +    console.log(`issue_comment.created`)
```suggestion
```

2023-11-06 09:56 UTC, fmvilas commented on lib/onboarding.js
> +2. Add this keywork in the description \`related to #ISSUE_BET_NUMBER\`
```suggestion
2. Add this keyword in the description \`related to #ISSUE_BET_NUMBER\`
```

2023-11-06 09:56 UTC, fmvilas commented on lib/onboarding.js
> +  console.log("Scope onboarding")
```suggestion
```

2023-11-06 09:56 UTC, fmvilas commented on lib/onboarding.js
> +To do so, you have to leave a comment in the issue or pull request with the following syntax::
```suggestion
To do so, you have to leave a comment in this issue or pull request with the following syntax:
```

2023-11-06 09:56 UTC, fmvilas commented on lib/onboarding.js
> +    console.log("Scope Comment added")
```suggestion
```

2023-11-06 09:56 UTC, fmvilas commented on lib/progress.js
> +    // const searchComment = await findPreviousComment(context, owner, repo, issueNumber, '/progress', false)
```suggestion
```

2023-11-06 09:56 UTC, fmvilas commented on lib/progress.js
> +    if (comment.body.includes('/progress') && !comment.user.login.includes('-bot')) {
```suggestion
    if (comment.body.includes('/progress') && !comment.user.login.endsWith('-bot')) {
```

2023-11-06 09:56 UTC, fmvilas commented on lib/scopes.js
> +    const regexSimple = /(Related\sto\s+(\S+)?#(\d+))/
This won't match URLs, just `#ISSUE_NUMBER`, which is great but sometimes the Pitch or Bet is in another repo so we need to be able to understand full URLs here too.

2023-11-06 09:56 UTC, fmvilas commented on lib/scopes.js
> +      console.log("Nothing to do in this issue")
```suggestion
```

2023-11-06 16:32 UTC, Amzani commented
@fmvilas thanks for your review, I've fixed a couple of stuffs

2023-11-07 15:55 UTC, Amzani commented
@fmvilas added deployment to fly.io / you should get an invitation by email.

2023-11-08 09:27 UTC, fmvilas approved these changes

2023-11-08 09:27 UTC, merged